package com.example.DMS.model;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name="employee"
    ,catalog="dmstask"
)
public class Employee  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Date birthDate;
     private String birthCity;
     private Integer code;
     private String department;
     private String jobTitle;
     private String directManager;
     private String contractType;
     private String status;

    public Employee() {
    }

    public Employee(String name, Date birthDate, String birthCity, Integer code, String department, String jobTitle, String directManager, String contractType, String status) {
       this.name = name;
       this.birthDate = birthDate;
       this.birthCity = birthCity;
       this.code = code;
       this.department = department;
       this.jobTitle = jobTitle;
       this.directManager = directManager;
       this.contractType = contractType;
       this.status = status;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="birthDate", length=10)
    public Date getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

    
    @Column(name="birthCity", length=45)
    public String getBirthCity() {
        return this.birthCity;
    }
    
    public void setBirthCity(String birthCity) {
        this.birthCity = birthCity;
    }

    
    @Column(name="code")
    public Integer getCode() {
        return this.code;
    }
    
    public void setCode(Integer code) {
        this.code = code;
    }

    
    @Column(name="department", length=45)
    public String getDepartment() {
        return this.department;
    }
    
    public void setDepartment(String department) {
        this.department = department;
    }

    
    @Column(name="jobTitle", length=45)
    public String getJobTitle() {
        return this.jobTitle;
    }
    
    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }

    
    @Column(name="directManager", length=45)
    public String getDirectManager() {
        return this.directManager;
    }
    
    public void setDirectManager(String directManager) {
        this.directManager = directManager;
    }

    
    @Column(name="contractType", length=45)
    public String getContractType() {
        return this.contractType;
    }
    
    public void setContractType(String contractType) {
        this.contractType = contractType;
    }

    
    @Column(name="status", length=45)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


